---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerberus
  namespace: cerberus
  labels:
    app: cerberus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cerberus
  labels:
    app: cerberus
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies", "ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cerberus
  labels:
    app: cerberus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cerberus
subjects:
  - kind: ServiceAccount
    name: cerberus
    namespace: cerberus
