apiVersion: v2
name: cerberus
description: Cerberus NGFW/UTM - Enterprise Next-Generation Firewall
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - firewall
  - ngfw
  - utm
  - ips
  - vpn
  - content-filter
  - security

home: https://github.com/penguintechinc/cerberus
sources:
  - https://github.com/penguintechinc/cerberus

maintainers:
  - name: Penguin Tech Inc
    email: support@penguintech.io

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: opensearch
    version: "2.x.x"
    repository: "https://opensearch-project.github.io/helm-charts"
    condition: opensearch.enabled
